#!/usr/bin/env node
const config = require('./config.json'),
	ex = require('./execute'),
	bar = require('./bar'),
	readable = require('./readable')

ex('df').then(out => {// | grep dev/sd
	out.split('\n').forEach(drive => {
		grep = /\/dev\/(sd[a-z]\d)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+%) (\/\S*)$/gm.exec(drive)
		if(grep == null) return
		console.log()
		console.log(`\x1b[96m${grep[1]}\x1b[0m mounted on \x1b[34m${grep[6]}\x1b[0m \x1b[33m${readable(grep[3], 2)}GB\x1b[0m of ${readable(grep[2], 2)}GB`)
		console.log(bar(grep[3], grep[2], ['\x1b[94m=', '-']))
	})
})