#!/usr/bin/env python3
import os
import misc

temps = os.popen("sensors -u").read()
temps = temps.split('\n')
lastline = False
out = ""

for line in temps:
    # print(repr(lastline), repr(line))
    if lastline == '':
        out += line+'\n'
    lastline = line

    if 'temp' in line and 'input' in line:
        line = line.split()
        out += " {} {}{:.1f}\x1b[0m\n".format(
            line[0],
            '\x1b[91m' if float(line[1])>80 else '\x1b[93m' if float(line[1])>65 else '\x1b[92m',
            float(line[1])
            )

print(out)