#!/usr/bin/env node
const config = require('./config.json'),
	ex = require('./execute')

ex(`sudo -H -u ${config.pm2_user} bash -c "pm2 jlist"`).then(out => {
	out = JSON.parse(out)

	console.log()
	console.log(`PM2 Services:`)
	for(let service of out){
		console.log(` \x1b[1m${service.name}\x1b[0m ${service.pm2_env.status != 'online' ? '\x1b[31m' : '\x1b[32m'}${service.pm2_env.status}\x1b[0m ${service.monit.cpu}% ${~~(service.monit.memory / 1024 / 1024)} MB${service.pm2_env.restart_time > 0 ? ` \x1b[33m${service.pm2_env.restart_time} ↺ \x1b[0m` : ''}`)	
	}
	
})
