#!/bin/bash
dest=/etc/update-motd.d
color=${1:-39}

cp *-* $dest/
cp misc.py $dest/

echo "color=\"\e[${color}m\"" > $dest/color

chmod -x $dest/*

chmod +x $dest/-header
chmod +x $dest/-logo
chmod +x $dest/-uptime
chmod +x $dest/-mounts
chmod +x $dest/-temps
chmod -x $dest/-services
chmod -x $dest/-pm2
chmod +x $dest/-updates-available
chmod +x $dest/-release-upgrade
chmod +x $dest/-unattended-upgrades
chmod +x $dest/-hwe-eol
chmod +x $dest/-fsck-at-reboot
chmod +x $dest/-reboot-required