#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with root privileges"
    exit 1
fi

dest=/etc/update-motd.d

# dependencies
apt install figlet python3 -y

# turn off stock motd news
systemctl stop motd-news.timer
systemctl disable motd-news.timer

# copy files to destination
cp *-* $dest/
cp misc.py $dest/

# set execute permissions
chmod -x $dest/*

chmod +x $dest/00-header
chmod +x $dest/05-logo
chmod +x $dest/10-uptime
chmod +x $dest/18-mounts
chmod +x $dest/19-temps
#chmod +x $dest/20-services
#chmod +x $dest/22-pm2
chmod +x $dest/88-esm-announce
chmod +x $dest/90-updates-available
chmod +x $dest/91-release-upgrade
chmod +x $dest/92-unattended-upgrades
chmod +x $dest/95-hwe-eol
chmod +x $dest/98-fsck-at-reboot
chmod +x $dest/98-reboot-required
